title: ""
#url: "https://ghodsi.me"
#baseurl: ""

markdown: kramdown

tracking_id: #

footer: yes
footer_url: mailto:zghodsi@ucsd.edu
footer_text: "send me a message: zghodsi [at] ucsd.edu"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "Publications"
   link: "publications"
